// Code generated by MockGen. DO NOT EDIT.
// Source: board/board.go
//
// Generated by this command:
//
//	mockgen -source=board/board.go -destination=mocks/board_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ship "awesomeProject2/ship"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBoardInterface is a mock of BoardInterface interface.
type MockBoardInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBoardInterfaceMockRecorder
	isgomock struct{}
}

// MockBoardInterfaceMockRecorder is the mock recorder for MockBoardInterface.
type MockBoardInterfaceMockRecorder struct {
	mock *MockBoardInterface
}

// NewMockBoardInterface creates a new mock instance.
func NewMockBoardInterface(ctrl *gomock.Controller) *MockBoardInterface {
	mock := &MockBoardInterface{ctrl: ctrl}
	mock.recorder = &MockBoardInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardInterface) EXPECT() *MockBoardInterfaceMockRecorder {
	return m.recorder
}

// CanPlaceShip mocks base method.
func (m *MockBoardInterface) CanPlaceShip(x, y, size int, horizontal bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanPlaceShip", x, y, size, horizontal)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanPlaceShip indicates an expected call of CanPlaceShip.
func (mr *MockBoardInterfaceMockRecorder) CanPlaceShip(x, y, size, horizontal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanPlaceShip", reflect.TypeOf((*MockBoardInterface)(nil).CanPlaceShip), x, y, size, horizontal)
}

// GetCells mocks base method.
func (m *MockBoardInterface) GetCells() [10][10]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCells")
	ret0, _ := ret[0].([10][10]string)
	return ret0
}

// GetCells indicates an expected call of GetCells.
func (mr *MockBoardInterfaceMockRecorder) GetCells() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCells", reflect.TypeOf((*MockBoardInterface)(nil).GetCells))
}

// GetShips mocks base method.
func (m *MockBoardInterface) GetShips() []*ship.Ship {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShips")
	ret0, _ := ret[0].([]*ship.Ship)
	return ret0
}

// GetShips indicates an expected call of GetShips.
func (mr *MockBoardInterfaceMockRecorder) GetShips() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShips", reflect.TypeOf((*MockBoardInterface)(nil).GetShips))
}

// HandleShoot mocks base method.
func (m *MockBoardInterface) HandleShoot(x, y int) (string, bool, ship.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleShoot", x, y)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(ship.Status)
	return ret0, ret1, ret2
}

// HandleShoot indicates an expected call of HandleShoot.
func (mr *MockBoardInterfaceMockRecorder) HandleShoot(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleShoot", reflect.TypeOf((*MockBoardInterface)(nil).HandleShoot), x, y)
}

// PlaceShip mocks base method.
func (m *MockBoardInterface) PlaceShip(x, y, size int, horizontal bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceShip", x, y, size, horizontal)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlaceShip indicates an expected call of PlaceShip.
func (mr *MockBoardInterfaceMockRecorder) PlaceShip(x, y, size, horizontal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShip", reflect.TypeOf((*MockBoardInterface)(nil).PlaceShip), x, y, size, horizontal)
}

// PlaceShipRandom mocks base method.
func (m *MockBoardInterface) PlaceShipRandom() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlaceShipRandom")
}

// PlaceShipRandom indicates an expected call of PlaceShipRandom.
func (mr *MockBoardInterfaceMockRecorder) PlaceShipRandom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceShipRandom", reflect.TypeOf((*MockBoardInterface)(nil).PlaceShipRandom))
}

// PrintBoard mocks base method.
func (m *MockBoardInterface) PrintBoard(showShips bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintBoard", showShips)
}

// PrintBoard indicates an expected call of PrintBoard.
func (mr *MockBoardInterfaceMockRecorder) PrintBoard(showShips any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintBoard", reflect.TypeOf((*MockBoardInterface)(nil).PrintBoard), showShips)
}
