// Code generated by MockGen. DO NOT EDIT.
// Source: game/game.go
//
// Generated by this command:
//
//	mockgen -source=game/game.go -destination=mocks/game_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	player "awesomeProject2/player"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameInterface is a mock of GameInterface interface.
type MockGameInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGameInterfaceMockRecorder
	isgomock struct{}
}

// MockGameInterfaceMockRecorder is the mock recorder for MockGameInterface.
type MockGameInterfaceMockRecorder struct {
	mock *MockGameInterface
}

// NewMockGameInterface creates a new mock instance.
func NewMockGameInterface(ctrl *gomock.Controller) *MockGameInterface {
	mock := &MockGameInterface{ctrl: ctrl}
	mock.recorder = &MockGameInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameInterface) EXPECT() *MockGameInterfaceMockRecorder {
	return m.recorder
}

// AddPlayer mocks base method.
func (m *MockGameInterface) AddPlayer(name string) *player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlayer", name)
	ret0, _ := ret[0].(*player.Player)
	return ret0
}

// AddPlayer indicates an expected call of AddPlayer.
func (mr *MockGameInterfaceMockRecorder) AddPlayer(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlayer", reflect.TypeOf((*MockGameInterface)(nil).AddPlayer), name)
}

// GetEnemy mocks base method.
func (m *MockGameInterface) GetEnemy() *player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnemy")
	ret0, _ := ret[0].(*player.Player)
	return ret0
}

// GetEnemy indicates an expected call of GetEnemy.
func (mr *MockGameInterfaceMockRecorder) GetEnemy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnemy", reflect.TypeOf((*MockGameInterface)(nil).GetEnemy))
}

// GetWinner mocks base method.
func (m *MockGameInterface) GetWinner() *player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWinner")
	ret0, _ := ret[0].(*player.Player)
	return ret0
}

// GetWinner indicates an expected call of GetWinner.
func (mr *MockGameInterfaceMockRecorder) GetWinner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWinner", reflect.TypeOf((*MockGameInterface)(nil).GetWinner))
}

// IsEnded mocks base method.
func (m *MockGameInterface) IsEnded() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnded")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnded indicates an expected call of IsEnded.
func (mr *MockGameInterfaceMockRecorder) IsEnded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnded", reflect.TypeOf((*MockGameInterface)(nil).IsEnded))
}

// Round mocks base method.
func (m *MockGameInterface) Round(x, y int) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Round", x, y)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Round indicates an expected call of Round.
func (mr *MockGameInterfaceMockRecorder) Round(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Round", reflect.TypeOf((*MockGameInterface)(nil).Round), x, y)
}

// SwitchMove mocks base method.
func (m *MockGameInterface) SwitchMove() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchMove")
}

// SwitchMove indicates an expected call of SwitchMove.
func (mr *MockGameInterfaceMockRecorder) SwitchMove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchMove", reflect.TypeOf((*MockGameInterface)(nil).SwitchMove))
}

// TakeMove mocks base method.
func (m *MockGameInterface) TakeMove() *player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeMove")
	ret0, _ := ret[0].(*player.Player)
	return ret0
}

// TakeMove indicates an expected call of TakeMove.
func (mr *MockGameInterfaceMockRecorder) TakeMove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeMove", reflect.TypeOf((*MockGameInterface)(nil).TakeMove))
}

// allShipsSunk mocks base method.
func (m *MockGameInterface) allShipsSunk(arg0 *player.Player) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "allShipsSunk", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// allShipsSunk indicates an expected call of allShipsSunk.
func (mr *MockGameInterfaceMockRecorder) allShipsSunk(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "allShipsSunk", reflect.TypeOf((*MockGameInterface)(nil).allShipsSunk), arg0)
}
