// Code generated by MockGen. DO NOT EDIT.
// Source: player/player.go
//
// Generated by this command:
//
//	mockgen -source=player/player.go -destination=mocks/player_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	player "awesomeProject2/player"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlayerInterface is a mock of PlayerInterface interface.
type MockPlayerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerInterfaceMockRecorder
	isgomock struct{}
}

// MockPlayerInterfaceMockRecorder is the mock recorder for MockPlayerInterface.
type MockPlayerInterfaceMockRecorder struct {
	mock *MockPlayerInterface
}

// NewMockPlayerInterface creates a new mock instance.
func NewMockPlayerInterface(ctrl *gomock.Controller) *MockPlayerInterface {
	mock := &MockPlayerInterface{ctrl: ctrl}
	mock.recorder = &MockPlayerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerInterface) EXPECT() *MockPlayerInterfaceMockRecorder {
	return m.recorder
}

// DoMove mocks base method.
func (m *MockPlayerInterface) DoMove(enemy *player.Player, x, y int) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoMove", enemy, x, y)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DoMove indicates an expected call of DoMove.
func (mr *MockPlayerInterfaceMockRecorder) DoMove(enemy, x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoMove", reflect.TypeOf((*MockPlayerInterface)(nil).DoMove), enemy, x, y)
}

// GiveUp mocks base method.
func (m *MockPlayerInterface) GiveUp() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GiveUp")
}

// GiveUp indicates an expected call of GiveUp.
func (mr *MockPlayerInterfaceMockRecorder) GiveUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveUp", reflect.TypeOf((*MockPlayerInterface)(nil).GiveUp))
}

// StatusPlayer mocks base method.
func (m *MockPlayerInterface) StatusPlayer() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusPlayer")
	ret0, _ := ret[0].(string)
	return ret0
}

// StatusPlayer indicates an expected call of StatusPlayer.
func (mr *MockPlayerInterfaceMockRecorder) StatusPlayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusPlayer", reflect.TypeOf((*MockPlayerInterface)(nil).StatusPlayer))
}
