// Code generated by MockGen. DO NOT EDIT.
// Source: ship/ship.go
//
// Generated by this command:
//
//	mockgen -source=ship/ship.go -destination=mocks/ship_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ship "awesomeProject2/ship"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShipInterface is a mock of ShipInterface interface.
type MockShipInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShipInterfaceMockRecorder
	isgomock struct{}
}

// MockShipInterfaceMockRecorder is the mock recorder for MockShipInterface.
type MockShipInterfaceMockRecorder struct {
	mock *MockShipInterface
}

// NewMockShipInterface creates a new mock instance.
func NewMockShipInterface(ctrl *gomock.Controller) *MockShipInterface {
	mock := &MockShipInterface{ctrl: ctrl}
	mock.recorder = &MockShipInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipInterface) EXPECT() *MockShipInterfaceMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockShipInterface) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockShipInterfaceMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockShipInterface)(nil).GetStatus))
}

// HandleShoot mocks base method.
func (m *MockShipInterface) HandleShoot(x, y int) (bool, ship.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleShoot", x, y)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(ship.Status)
	return ret0, ret1
}

// HandleShoot indicates an expected call of HandleShoot.
func (mr *MockShipInterfaceMockRecorder) HandleShoot(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleShoot", reflect.TypeOf((*MockShipInterface)(nil).HandleShoot), x, y)
}
